backend:
  name: git-gateway
  branch: main

local_backend: true

locale: de

media_folder: static/img
public_folder: /img

collections:
  - name: "wichtig"
    label: "Datenschutz & CO."
    format: "frontmatter"
    extension: 'md'
    folder: "content/wichtig"
    create: true
    sortable_fields: ["title"]
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - name: "seiten"
    label: "Seiten"
    format: "frontmatter"
    extension: 'md'
    folder: "content/seiten"
    create: true
    sortable_fields: ["title"]
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - label: "Inhaltsblock"
        name: "content"
        widget: "list"
        fields:
          - { label: "Titel", name: "title", widget: "string", required: false }
          - { label: "Inhalt", name: "body", widget: "markdown", required: false }
          - label: Bilder
            name: "images"
            widget: "list"
            fields:
              - { label: "Bild", name: "image", widget: "image", required: false }
      
  - name: "portfolio"
    label: "Portfolio"
    format: "frontmatter"
    extension: 'md'
    folder: "content/portfolio"
    create: true
    sortable_fields: ["title"]
    editor:
      preview: false
    fields:
      - { label: "Portfolio Bild", name: "portfolioImage", widget: "image", required: false}
      - { label: "Portfolio Vorschau Video", name: "portfolioVideo", widget: "image", required: false }
      - { label: "Portfolio Vimeo Video", name: "portfolioVimeoLink", widget: "string", required: false }
      - { label: "Pojekttitel", name: "title", widget: "string", required: false }
      - { label: "Kategorie", name: "category", widget: "string", required: false }
      - { label: "Kunde", name: "customer", widget: "string", required: false }
      - { label: "Position", name: "position", widget: "number", required: false }
      - { label: "Projektbeschrebung", name: "description", widget: "markdown", required: false }
      - label: "Zusatzinformationen"
        name: "additionalInformation"
        widget: "list"
        fields:
          - { label: "Titel", name: "title", widget: "string", required: false }
          - { label: "Inhalt", name: "body", widget: "markdown", required: false }
      - label: "Bilder"
        name: "images"
        widget: "list"
        fields:
          - { label: "Bild", name: "image", widget: "image", required: false }

  - name: "auszeichnungen"
    label: "Auszeichnungen"
    format: "frontmatter"
    extension: 'md'
    folder: "content/auszeichnungen"
    create: true
    sortable_fields: ["title"]
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string", required: false }
      - { label: "Auszeichnung", name: "image", widget: "image", required: false }
  
  - name: "kontaktdaten"
    label: "Kontaktdaten"
    format: "json"
    folder: "content/kontaktdaten"
    create: true
    sortable_fields: ["title"]
    editor:
      preview: false
    fields:
      - { label: "Firmenname", name: "company_name", widget: "string", required: false }
      - { label: "Straße", name: "street", widget: "string", required: false }
      - { label: "PLZ", name: "zip", widget: "string", required: false }
      - { label: "Ort", name: "city", widget: "string", required: false }
      - { label: "Telefon", name: "phone", widget: "string", required: false }
      - { label: "E-Mail", name: "email", widget: "string", required: false }